### ISSUE TITLE
Tracking issue: Xamarin.Forms issues on GTK

### ISSUE THREAD

**Issue by dsyme** [fsprojects/Fabulous#623]
Xamarin.Forms on GTK has lots of issues, enough that you can really only use a simple set of controls, and even then have to be careful w.r.t styling 
Here's a list of things I noticed in AllControls.fs when working on #621. This is a tracking issue for this as it's not Fabulous-specific, though it's possible the property updates Fabulous is requesting exposes these specific bugs in Xamarin.Forms Gtk support.

GTK on Mac or Windows:

* [ ] Button: not always the correct size, often near-zero or randomly sized
* [ ] Image: not showing 
* [ ] SearchBar: hitting "return" doesn't trigger change event.  You have to hit the "search" button 
* [ ] CarouselPage: only the first page shows
* [ ] MasterDetailPage:  odd behaviour, doesn't really work
* [ ] InfiniteList: causes repeated updates then a crash when you navigate away from the page
* [ ] Animations: do not work, presumably a GTK limitation
* [ ] SkiaSharp : nosupport
* [ ] OxyPlot: support
* [ ] Map:  support didn't work, at least on Mac
* [ ] Shell: no support
* [ ] CarouselView: no support
* [ ] RefreshView: no way to trigger refresh

GTK specifically on Mac:

* [ ] had to start the application from the command line, didn't start from VS for Mac (presumably you can set the launch path explicitly)
* [ ] Other: asserts like `(AllControls.Gtk:6664): Gtk-CRITICAL **: void gtk_container_remove(GtkContainer *, GtkWidget *): assertion `GTK_IS_TOOLBAR (container) || widget->parent == GTK_WIDGET (container)' failed`

GTK specifically on Windows:

* [ ] Entry: weird sizing 
* [ ] Popup: the buttons on the popup are all messed up

**Comment by dsyme** [comment]
(I'll make a separate issue for things I noticed on UWP, macOS and WPF)
