### ISSUE TITLE
Tracking issue: Xamarin.Forms issues on macOS

### ISSUE THREAD

**Issue by dsyme** [fsprojects/Fabulous#624]
Xamarin.Forms on macOS has issues. This is a tracking issue as it's not Fabulous-specific

Here's a list of things I noticed in AllControls.fs when working on #621

* [ ] Images in AllControls didn't seem to expand and fill in the same way as other platforms
* [ ] ListView: No items appear
* [ ] ListViewGrouped: No items appear
* [ ] CarouselPage: Couldn't carousel through pages
* [ ] NavigationPage: "back" didn't seem to work correctly
* [ ] Shell: not supported
* [ ] CollectionView: not supported
* [ ] CarouselView: not supported
* [ ] Effects: not supported
* [ ] RefreshView:  a drag down on the mouse changed the visuals but didn't seem to actually trigger a refresh
* [ ] OxyPlot: not supported
