### ISSUE TITLE
Tracking Issue: Xamarin.Forms on WPF

### ISSUE THREAD

**Issue by dsyme** [fsprojects/Fabulous#625]
Xamarin.Forms on WPF has some issues and missing functionality

Here's a list of things I noticed in AllControls.fs when working on #621. This is a tracking issue for this as it's not Fabulous-specific, though it's possible the property updates Fabulous is requesting exposes these specific bugs in Xamarin.Forms WPF support.

* [ ] Grid: doesn't always re-create correctly after flicking to a page with a grid and then back again
* [ ] Shell: not supported on last test
* [ ] CollectionView: not supported on last test
* [ ] RefreshView: no way to trigger refresh by default
* [ ] SkiaSharp: not supported
* [ ] OxyPlot: not supported
