### ISSUE TITLE
Tracking Issue: Xamarin.Forms on UWP

### ISSUE THREAD

**Issue by dsyme** [fsprojects/Fabulous#626]
Xamarin.Forms on UWP has some issues and missing functionality. The list below is based on a walkthrough of using AllControls.fs. 

Note: This is a tracking issue for this as these things are not Fabulous-specific (though it's possible the property updates Fabulous is requesting exposes these specific bugs).  It's also possible these things have been fixed since last check.

* [ ] Grid: doesn't always re-create correctly after flicking to a page with a grid and then back again
* [ ] Shell: not supported (on last test)
* [ ] CollectionView: not supported (on last test)
* [ ] RefreshView: no way to trigger refresh by default
* [ ] SkiaSharp: not supported (on last test)
* [ ] OxyPlot: not supported (on last test)
